# Generated by Django 5.0.6 on 2024-06-20 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choiceform',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswerform',
            name='selected_choice',
        ),
        migrations.RemoveField(
            model_name='questionform',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='QuizForm',
        ),
        migrations.RemoveField(
            model_name='useranswerform',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswerform',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='useranswerform',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChoiceForm',
        ),
        migrations.DeleteModel(
            name='QuestionForm',
        ),
        migrations.DeleteModel(
            name='UserAnswerForm',
        ),
    ]
