# Generated by Django 5.0.6 on 2024-06-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_course_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
